// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Demo;

// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface testPrx extends Ice.ObjectPrx
{
    public String execute(String mth, String cmd);

    public String execute(String mth, String cmd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_execute(String mth, String cmd);

    public Ice.AsyncResult begin_execute(String mth, String cmd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_execute(String mth, String cmd, Ice.Callback __cb);

    public Ice.AsyncResult begin_execute(String mth, String cmd, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_execute(String mth, String cmd, Callback_test_execute __cb);

    public Ice.AsyncResult begin_execute(String mth, String cmd, java.util.Map<String, String> __ctx, Callback_test_execute __cb);

    public String end_execute(Ice.AsyncResult __result);
}
